sudo: required
services:
  - docker

before_install:
  - docker build -t maniks/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run maniks/react-test npm test -- --coverage
after_success:
  - docker build -t maniks/multi-client ./client
  - docker build -t maniks/multi-nginx ./nginx
  - docker build -t maniks/multi-server ./server
  - docker build -t maniks/multi-worker ./worker
  #Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push to docker hub
  - docker push maniks/multi-client
  - docker push maniks/multi-nginx
  - docker push maniks/multi-server
  - docker push maniks/multi-worker
